name: SBOM Generator

on:
  push:
    branches: [ "sbom-generation" ]

  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: anchore/sbom-action@v0
        with:
            path: /github/workspace
            artifact-name: sbom.spdx
            dependency-snapshot: true
            upload-artifact: true
            